<?php
/**
 *    Copyright 2018 Humanswitch
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
/**
 * @var \Humanswitch\Consentcookie\Block\Consentcookie $block
 */
if ($block->isEnabled() && $configuration = $block->getConsentCookieConfiguration()): ?>
    <script type="text/javascript">
        require([
            'jquery',
            '<?php echo $block->getScriptSource() ?>'
        ], function ($, ConsentCookie) {
            'use strict';

            window.ConsentCookie = ConsentCookie;
            window.ConsentCookie.init(<?php echo $configuration ?>);

            var CCInitEvent = new CustomEvent('CCInit', {
                detail: {
                    ConsentCookie: ConsentCookie,
                }
            });

            window.ConsentCookie.on('connection', function (e) {
                if (e.id == 'ga' && e.state == 'enabled') {
                    window.dispatchEvent(CCInitEvent);
                }
            });

            window.dispatchEvent(CCInitEvent);
        });
    </script>
<?php endif; ?>
