<?php
/**
 *    Copyright 2018 Humanswitch
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/**
 * @var \Humanswitch\Consentcookie\Block\Configurator $block
 */
if ($block->isEnabled()) : ?>

    <div id="ccc-container"></div>

    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function (event) {
            if (typeof CCC !== "undefined") {
                var CCConfigurator = new CCC('#ccc-container');

                <?php if ($configuration = $block->getConsentCookieConfiguration()) : ?>
                CCConfigurator.setConfig(<?php echo $block->escapeJsQuote($configuration) ?>);
                <?php endif; ?>

                CCConfigurator.setOptions({
                    copyButton: false,
	                generator: 'mag2',
                    appsEndpoint: 'https://cdn.humanswitch.services/cc/configurator/configurator.json'
                });

                CCConfigurator.onChange(function (configurator, config) {
                    document.getElementById('consentcookie_configurator_settings_configuration').value = JSON
                        .stringify(config, null, 2);
                }).mount();
            } else {
                document.getElementById("ccc-container").textContent = '<?php echo $block->escapeHtml(__('Could not load the ConsentCookie configurator... Contact support for more information.')) ?>';
            }
        });
    </script>
<?php else : ?>
    <p><?php echo $block->escapeHtml(__('Enable the ConsentCookie configurator in order to easily configure ConsentCookie.')) ?></p>
<?php endif; ?>
